#
# _config.yml for ffi blog
#

exclude: [ "CNAME", "README.md", "LICENSE.txt", "tmp", "*.sh", "**/*_src*" ]
permalink: /:year/:month/:day/:title/index.html
production_url: http://blog.fileformat.info
title : FileFormat.Info Blog
